version: "3"
services:
  postgresql:
    image: postgres:10
    ports:
      - 5433:5432
    environment:
      - PGDATA=/postgresql
      - PG_PASSWORD=postgres
    volumes:
      - ./tmp/system/postgresql:/postgresql
